# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CRUD app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./crud-mysql

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Install pm2
      run: npm install pm2@latest -g
      working-directory: ${{ env.working-directory }}

    - name: Start crud app
      run: pm2 start app.js && pm2 save
      working-directory: ${{ env.working-directory }}

#    - name: Restart PM2
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.AWS_SERVER_HOST }}
#        username: ec2-user
#        key: ${{ secrets.SERVER_DEPLOY_SSH_KEY }}
#        proxy_host: ${{ secrets.AWS_PROXY_HOST }}
#        proxy_username: ec2-user
#        proxy_key: ${{ secrets.AWS_PROXY_KEY }}
#        proxy_port: 22
#        port: 22
#        script: "cd crud-mysql && npm install && pm2 reload ecosystem.config.js --env production"

